# Site settings
name: Spiros Liaskonis
title: Spiros Liaskonis
description: An aspiring computer engineer, driven by curiosity and a love for building, optimizing, and learning.
url: https://sliaskonis.github.io/
baseurl: ''
email: spiros1239@gmail.com
cover: https://sliaskonis.github.io/img/og.png
logo: https://sliaskonis.github.io/img/emojis/technologist.png
resume: https://sliaskonis.github.io/resume.pdf
social:
  - title: email
    url: mailto:spiros1239@gmail.com
  - title: twitter
    url: https://twitter.com/SpirosLiaskonis
  - title: github
    url: https://github.com/sliaskonis
  - title: linkedin
    url: https://www.linkedin.com/in/spiros-liaskonis-a173281a2/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
